modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Cursee-Development"
logoFile="icon.png"

[[mods]]
modId="danger_close"
version="3.0.2"
displayName="Danger Close"
displayURL="https://github.com/Cursee-Development"
authors="Lupin, Cursee Development"
description='''You're standing a little close to that torch!'''
credits='''Credit to Jared (Bookshelf) and Serilum (Collective).'''

[[dependencies.danger_close]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6]"
    ordering="NONE"
    side="BOTH"

[[dependencies.danger_close]]
    modId="neoforge"
    type="required"
    versionRange="[20.6.0,)"
    ordering="NONE"
    side="BOTH"

# MonoLib dependency
[[dependencies.danger_close]]
    modId="monolib"
    type="required"
    versionRange="[1.2.0,)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "danger_close.neoforge.mixins.json"