modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Cursee-Development"
logoFile="icon.png"

[[mods]]
modId="example"
version="1.0.0"
displayName="Example"
displayURL="https://github.com/Cursee-Development"
authors="Cursee Development"
description='''TEMPLATE - Not for distribution'''
credits='''Credit to Jared (Bookshelf) and Serilum (Collective).'''

[[dependencies.example]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6]"
    ordering="NONE"
    side="BOTH"

[[dependencies.example]]
    modId="neoforge"
    type="required"
    versionRange="[20.6.0,)"
    ordering="NONE"
    side="BOTH"

# MonoLib dependency
[[dependencies.example]]
    modId="monolib"
    type="required"
    versionRange="[1.2.0,)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "example.neoforge.mixins.json"